### ISSUE TITLE
建议增加认领机制

### ISSUE THREAD

**Issue by HDT3213** [CN-annotation-team/redis7.0-chinese-annotated#40]
如题，可以用 issue 或者 projects 功能认领要翻译的模块，避免多人重复翻译同一个源文件

**Comment by ncghost1** [comment]
是的这个我当初也想过提个issue说明你接下来要注释的部分（这个部分是未曾有过注释的，修改已有的注释不用），但是我最后好像忘记写到README里了，好像是突然担心了一下执行度不够。 @enjoy-binbin 你认为这么做可以吗？
edited：已发起相关 PR #41，可以移步到 PR 讨论此问题。

**Comment by enjoy-binbin** [comment]
所以现在是有遇到多人重复翻译的问题么

有issue的话是可以，普通用户可以通过issue来说认领

另外我觉得单独pr不一定说提了就要合并，可以是一个wip的状态，用户可以一直提交增量的commit 而不一定是说等文件全部写完才提交

另外据我所知大部分人不会怎么关心readme，不会保持自己的fork和upstream保持同步，所以在readme里加人家有点难注意

更需要大家建立的一种自觉的方式是，看issue 例如可以是置顶的，看prs，可以是一直增量的从标题里看谁认领了这样

另外我个人其是觉得重复劳作其实影响不大，每个人做注释都是他自己的理解和认识，和别人冲撞其实问题不大，把理解输出成注释跟单看别人的注释其实差别很大，有冲撞相互之间看哪种更好其实也很能加深理解

我们现在有的一个主要问题是，注释覆盖还是太少，然后要保证注释质量
